model_list:
  # Configuration for Claude model
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: anthropic/claude-3-5-sonnet

  # Configuration for OpenAI model
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini

# Guardrails configuration using Presidio
guardrails:
  - guardrail_name: "presidio-pii-guard"
    litellm_params:
      guardrail: presidio  # Use Microsoft Presidio for PII masking
      mode: "pre_call"     # Apply before the model call
      output_parse_pii: True  # Replace masked tokens with original values
      default_on: true     # Execute on all LLM requests

      # Path to the JSON file of recognizers
      presidio_ad_hoc_recognizers: "./hooks/pii_recognizers.json"

      presidio_entities_to_analyze:
      # Standard Presidio entities
          - "PERSON"
          - "PHONE_NUMBER"
          - "EMAIL_ADDRESS"
          - "CREDIT_CARD"
          - "LOCATION"
          - "DATE_TIME"
          - "URL"
          - "IP_ADDRESS"
          # Italian entities
          - "CODICE_FISCALE"
          - "PARTITA_IVA"
          - "CARTA_IDENTITA"
          - "PATENTE_GUIDA"
          - "PASSAPORTO"
          - "IBAN"
          # Swiss entities
          - "AHV_AVS_NUMBER"
          - "SWISS_ID_CARD"
          - "SWISS_PASSPORT"
          - "SWISS_VAT_NUMBER"
          - "SWISS_IBAN"
          # Additional entities
          - "US_BANK_NUMBER"

      # Advanced settings for improved accuracy
      presidio_threshold: 0.2  # Lower confidence threshold to increase sensitivity
      presidio_context_words: 5  # Increase the number of context words
      presidio_allow_list: []  # List of exceptions (values not to be masked)

# LiteLLM settings
litellm_settings:
  # Enable for detailed debugging
  set_verbose: True
  # Proxy configuration
  drop_params: True
  max_parallel_requests: 100
  num_workers: 8

# General settings
general_settings:
  store_model_in_db: true
  store_prompts_in_spend_logs: true
  # Maximum wait time for model responses
  request_timeout: 600
